### ISSUE TITLE
Reversed w-Wessim args "-w" and "-y" in w.wessim.py script?

### ISSUE THREAD

**Issue by FilipeFerreiraMOCHSL** [GeorgetteTanner/w-Wessim#1]
Greetings,

Thanks for this new version, which I installed on _02/15/2021_!

I think the args **"-y"** and **"-w"** are reversed in _"w-wessim.py"_ script (**lines 29 and 30, respectively**), right?

The "README.md" doc says:
_-w_   Minimum required fraction of probe match to be hybridized. (default: 50)
_-y_   Penalty weight for indel in the hybridization. (default: 2)

However, in the script it seems the **"-y"** takes the value that users think are attributing to **"-w"** and vice-versa.

Thank you!
Filipe Ferreira dos Santos

**Comment by GeorgetteTanner** [comment]
Hi Filipe

Thanks for pointing out this error. It is indeed an error in the README file which I have now corrected.

You may also be interested in using w-Wessim2 which I have recently uploaded (https://github.com/GeorgetteTanner/w-Wessim2). It uses the Reseq error model instead of GemSIM's to produce more realistic sequencing errors, and is also more computationally efficient.

Let me know if you have any more issues with either.

Best regards,
Georgette

**Comment by FilipeFerreiraMOCHSL** [comment]
Hi Georgette,

You're welcome!

Thanks for sharing w-Wessim2! I'll certainly use this newer version in future analyses.

If I understood it correctly, there are some major differences between them basically regarding the steps in the introduced "Reseq" error model, right?

Anyway, I'm sure users should have no problems migrating to this new version!

Best regards,
Filipe

**Comment by GeorgetteTanner** [comment]
Hi Felipe

Yes you are right, w-Wessim2 requires the user to run Reseq modules before and after the w-Wessim2 script to run the full pipeline. The first Reseq modules analyse the genome sequence to create a systematic errors profile for it, w-Wessim2 then selects fragment positions for sequencing and combines these with the corresponding portions of the error profile into an output. This is then used by another Reseq module to incorporate appropriate errors into the reads. 

I hope it's useful to you!

Best regards,
Georgette

**Comment by FilipeFerreiraMOCHSL** [comment]
Hi Georgette,

Thank you for the explanation, I'm sure it will be very useful!

Best,
Filipe
